### ISSUE TITLE
[rest-service] Utworzyć wrapper do api RESTowego 

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#39]
Mamy juz proste wrappery, które ułatwiają tworzenie serwera WWW. Popatrzcie na kod serwisu chat - pojawia tam się mnóstwo redundantnych wywołań, aby obsłużyć GET i POST dla danego typu zasobu. Musimy napisać zestaw funkcji, które ułatwią ten proces :) 
Ma to być channel prometeuszowy - czyli zdefiinowany jako chip i umieszczony w prometheus-modules. 
Przykłady tworzenia channela znajdują się w modułach `www-server` i `http`.
Chip ten oczywiście musi wymagać channela www-server.
Channel powinien mieć metodę
* `createResource`, która przyjmuja argumenty:
    - `url` - string, np. "/api/v1/chat/message"
    - `bindings` - obiekt. Wiąże metodę z eventem w serwisie. Przykład:
```
{
    "POST": {
            "service": "chat",
            "event": "new-message"
     }
}
```
Jak łatwo się domyślić, tak skonstruowany channel przy zapytaniu `POST` na  `/api/v1/chat/message` odpali event `new-message` z chipa typu service `chat`. Jako payload do tego eventu wysyła sparsowany z JSON payload zapytania POST.

**Comment by theadimar21** [comment]
51a7deb
