### ISSUE TITLE
[chat-message] Błąd przy zapytaniu GET

### ISSUE THREAD

**Issue by simplypixi** [groovy354/Prometheus#44]
Po wykonaniu GET'a na /lolo2, wywala w terminalu błąd następującej treści:
```
Possibly unhandled Error: ===errorr=== type 'chat-message' does not have a field with a name 'name'
```

**Comment by theadimar21** [comment]
Obecnie terminal wywala `Possibly unhandled ReferenceError: ResourceManager is not defined
    at Object.create (/home/adrian/Dokumenty/Prometheus/bin/prometheus-modules/database-view/database-view.js:12:3)`

**Comment by groovy354** [comment]
Ten problem nie tyczy się kodu po refaktoryzacji - ponieważ nowy kod zdaje się nie robić walidacji wartości pól ;p
