### ISSUE TITLE
Dispatchery

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#50]
Aktualnie po refaktoryzacji działa tylko dispatcher do trybu lokalnego. Należy tak pospawać prometeuszowe rury, aby działały też dispatchery do trybu db, biz, web. 
 * [x] `prometheus-core` ma metodę `start`, która przyjmuje trzy argumenty, wyznaczające aktualny tryb działania Prometeusza. Należy jej wywołanie w index.js zmienić tak, aby czytał parametry wywolania z terminala i przekazywał odpowiednie wartości do `prometheus-core.start`
 * [x] sprawić, aby działał dispatcher-db
 * [x] sprawić, aby działał dispatcher-biz
 * [x] sprawić, aby działał dispatcher-web

**Comment by Delfinek** [comment]
W tej chwili funkcja start z promotheus-core akceptuje następujujące sposoby uruchamiania 
1. "node ."
2. "node . local"
3. "node . distributed db"
4. "node . distributed biz"
5. "node . distributed web"

Wszystkie warstwy się odpalają, ale dipatcherom rozproszonym brakuje odpowiednich funkcji. W dipatcherze lokalnym opisaliśmy, które funkcje powinny się znaleźć w dispatcherze któej warstwy. Każda warstaw ma skopiowane z lokalnego dispatchera funkcje, które czekają na uzupełnienie przez kogoś kto rozumie ideę rozproszenia naszego kodu na 3 warstwy.

**Comment by Delfinek** [comment]
Z Kubą wyeliminowaliśmy błędy. Niestety trzeba było zmienić funkcję list_resources_by_type w pliku ResourceManager - pociąga to za sobą konieczność wprowadzenia zmian w dispatcherze trybu lokalnego. Do zamknięcia issue#50 pozostało
[] poprawienie dispatchera local
[] przetestowanie w różnych sytuacjach

**Comment by groovy354** [comment]
Zamykam, bo funkcjonalność już skończyliśmy. Wszelkie błędy działania zgłaszajmy jako osobne issues. Ostatni commit do tego issue - 1ddcbc1104434f44b5aa68c
