### ISSUE TITLE
Rzutowanie typu prometheus_id

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#54]
Aktualnie metoda DELETE przyjmuje tylko prometheus_id  w postaci integera. Jeżeli dostanie integera zawiniętego w `"`, to nie znajduje obiektu. Trzeba tak poprawić database_query, aby można było usuwać zarówno po prometheus_id w postaci stringa, jak i integera

**Comment by simplypixi** [comment]
Ejj... już jest spoko, bo parsujemy prometheus_id. Bezpośrednio przed
wykonaniem query. ;)

**Comment by groovy354** [comment]
Owszem, ale robimy to w warstwie interfejsu, a powinniśmy w klasie odpowiedzialnej za zapytania do bazy danych :)

**Comment by simplypixi** [comment]
Nie, nie. W webowej wszystko jest ok i tego parseInt można wywalić - bo
wciąga Int. Dodatkowo dodaliśmy z Adrianem parsowanie przed wykonaniem
zapytania do bazy. ;)

**Comment by groovy354** [comment]
Ostatecznie rozwiązane w 5b3ae2b0bce
