### ISSUE TITLE
Metoda Log-in i log-out

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#56]
Należy utworzyć channel, który zakłada handler dla dwóch URL:
* [x] `POST /login` - zapytanie POST wysłane na ten URL utworzy nam odpowiednią zmienną sesyjną i umieści ją w Cookies (jeżeli parametry `username` i `password` są prawidłowe)
* [x] `POST /logout` - zapytanie POST na ten URL niszczy aktualną sesję (wczytaną z Cookies)

**Comment by Delfinek** [comment]
Obsługa cookies.
---------------------
Do istniejącego cookies dostajemy się następująco:
request.state.NazwaNaszegoCookies

**Comment by Delfinek** [comment]
Działa przez Postmana, trzeba postawić formularz.

**Comment by simplypixi** [comment]
Formularz gotowy.
logowanie: /login.html

**Comment by Delfinek** [comment]
A czy mamy opcje wylogowania?
