### ISSUE TITLE
Zarządzanie użytkownikami - interfejs graficzny

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#58]
Stworzenie interfejsu graficznego (html, js) do zarządzania użytkownikami

**Comment by simplypixi** [comment]
Dobra. Niech Ci będzie Kuba. ;p

**Comment by groovy354** [comment]
Masz ważniejsze rzeczy do roboty! Twój progress czeka

**Comment by groovy354** [comment]
Rozwiązane w f5bfa3e2a0327c158
