### ISSUE TITLE
Zarządzanie uprawnieniami - API

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#59]

**Comment by simplypixi** [comment]
Obsłyga zarządzania uprawnieniami dodana. Od tej pory każdy zasób ma swój access_mode i acces_mode_args. Domyślnie, jeśli nie przypiszemy mu żadnej wartości, access_mode jest ustawiany na private. Access_mode_args domyślnie jest pustą tablicą. Możemy mu przypisać wartości: (tutaj ładnie proszę o pomoc @groovy354 , bo zapomniałem dokładnych nazw). Access_mode_args przypisujemy wartość, tylko wtedy gdy ustawiamy tryb na private - nie jest to wymagane.

**Comment by groovy354** [comment]
`access_mode` może mieć dwie wartości:
 * public
 * private

`public` nie przyjmuje żadnych argumentów. W przypadku, gdy `access_mode` jest ustawiony na `private`, to `access_mode_args` jest tablicą id-ków użytkowników, którzy mają dostęp do tego zasobu :)
