### ISSUE TITLE
[drobne] Liczba mnoga w adresach do restowego API

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#70]
Sprawdzić, czy kluczowy człon URLów naszego REST-owego api dla każdego typu zasobu jest rzeczownikiem w liczbie mnogiej - np. powinno być 
>   /api/v1/user**s**

zamiast 

>   /api/v1/user

:)

**Comment by Delfinek** [comment]
users poprawione, zotałao jeszcze conversation/conversations do sprawdzenia ;)
