### ISSUE TITLE
[REST] Przy tworzeniu zasobu zawsze ustawiać owner_id

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#74]
Aktualnie gdy tworzymy zasób za pomocą RESTowego api, nie przekazujemy argumentu `owner_id` do metody `create_resource` w ResourceManager. Należy wprowadzić takie zmiany do channel-u `REST`, aby przed utworzeniem zasobu sprawdzał po id sesji jaki użytkownik tworzy dany zasób i id tego użytkownika przypisywał do zasobu (poprzez argument `owner_id` przekazany do metody `create_resource`)

**Comment by simplypixi** [comment]
Zrobione ;)
Dodatkowo został zmieniony SessionManager. Teraz nie przechowuje username, ale userdata_id. Została również dodana do niego nowa metoda: get_user_id(), która jako argument przyjmuje klucz sesji.
Od teraz aby dodać konwersację trzeba się najpierw zalogować - jeśli ktoś nie jest zalogowany to zostanie automatycznie przekierowany na stronę logowania przy próbie dodania nowej konwersacji. Jeśli użytkownik jest zalogowany to konwersacja zostaje dodana, a id dodającego zostaje przypisane pod klucz "owner" tej konwersacji.

**Comment by groovy354** [comment]
Zmieniłem wartość przechowywaną w SessionManager z userdata_id (wskaźnik na resource) na `user_id`
Odnotowałem także, abym pomyślał nad poprawą nomenklatury... :)

ostatni commit z tego brancha to e57bc7edb2d91
