### ISSUE TITLE
[http easter egg] I'm a teapot 

### ISSUE THREAD

**Issue by groovy354** [groovy354/Prometheus#78]
Prometeusz musi mieć wsparcie dla kodu http 418 - I'm a teapot

**Comment by simplypixi** [comment]
Haha, myślałem o tym robiąc projekt na restowe. ;p

**Comment by simplypixi** [comment]
Ma zwracać ten kod na jakieś konkretnie zapytanie na specjalny adres? Niezbyt rozumiem zasadę używania tego kodu, ale z chęcią doklepię parę linijek kodu. ;)

**Comment by groovy354** [comment]
418 jest zwracany wtedy, kiedy zostanie wysłane żądanie o przygotowanie
kawy, ale serwer jest czajnikiem do herbaty i nie potrafi robić kawy :>
Proponuję 'api/v1/make_coffee'

**Comment by simplypixi** [comment]
No tak :P To po prostu źle zrozumiałem. Czas poćwiczyć angielski. ;)

**Comment by simplypixi** [comment]
Done.
